# @package _global_
config:
  MODEL:
    name: vgg16 #resnet50
    weight: imagenet
  EXPLANATION:
      method: ["IntegratedGradients", "LayerGradCam"] #LayerGradCam", "IntegratedGradients"] 
      layer: features[26] #layer4[2].conv3 # According the architecture
  DATA:
      type: [diskfile]
      loader: ImageFolder
      root: "/ds/images/imagenet/val"
      n_samples: 2
      size: (240,240)
  EVALUATION: ["RegionPerturbation", "RegionPerturbationThreshold"]
  OUTPUT: /netscratch/kadir/quantus




